### PR TITLE
Add offset (math + basic render changes)

### PR DESCRIPTION
**Pull request by samneff72**
Hi Sam - I updated the script to add an offset by moving the cy declaration into the update function and adding an h term in the same coordinate system that you've been using (starting from the pivot). Runs locally, test it before you merge of course. 

I am not confident about adding a new line to the group to indicate the robot being connected to the bar, so just pushing the core function update over for now. 

Thanks for writing this! Good clean widget.

### CODE REVIEW

**Comment by Samcfuchs** [comment]
Hi, thanks for this! It looks great and I'm going to approve it and add some lines, but I do have one question--are you 100% sure this math works? It looks good but something tells me it ought to be more complicated.

**Comment by samneff72** [comment]
When we make the assumption of rigid attachment, the CG doesn't move
relative the truss, so the new location of the mass can be added to the
truss CG calculation in exactly the same way.

I'm not allowing for some small amount of non-rigidity or sliding motion;
THAT would be complicated! :-) We're just looking for a first-order
calculation....


Best Regards,
Sam Neff

**Comment by samneff72** [comment]
Added lines that work on my local copy, pushed an update to Github.
Apologies if you were already working on it...

Best Regards,
Sam Neff

**Comment by Samcfuchs** [comment]
Thanks for your help!

**Pull request merged**
